included:
  - OneRM

file_length: 403
function_body_length: 65
identifier_name:
  excluded:
    - to
line_length:
  error: 500
  ignores_comments: true
  ignores_function_declarations: true
  warning: 149
type_body_length:
  warning: 206
force_try:
  severity: warning
force_cast: warning
statement_position:
identifier_name:
  min_length: 1
