# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build project"
  lane :build do
    build_ios_app(
      skip_codesigning: false,
      export_method: "ad-hoc",
      skip_package_ipa: true,
      destination: "platform=iOS Simulator,OS=13.0,name=iPhone 11 Pro Max",
      scheme: "OneRM App Store"
    )
  end
end
