default_platform(:ios)

platform :ios do
  desc "Build ad-hoc project"
  lane :adhoc do
    build_ios_app(
      skip_codesigning: false,
      export_method: "ad-hoc",
      skip_package_ipa: true,
      destination: "platform=iOS Simulator,OS=13.0,name=iPhone 11 Pro Max",
      scheme: "OneRM App Store"
    )
  end
end
